### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{ru.shirobokov.ecgtests/ru.shirobokov.ecgtests.presentation.HostActivity}

### ISSUE THREAD

**Issue by DimaKoz** [ShirobokovNE/ECG-tests#1]
Добрый вечер.
Происходит падение приложения.
[Лог](https://github.com/ShirobokovNE/ECG-tests/files/3831992/log_and.txt) прикрепил.

**Comment by ShirobokovNE** [comment]
Добрый вечер. Собирали релизную версию?

**Comment by ShirobokovNE** [comment]
> Добрый вечер.
> Происходит падение приложения.
> [Лог](https://github.com/ShirobokovNE/ECG-tests/files/3831992/log_and.txt) прикрепил.
Добрый вечер. Собирали релизную версию?
